name: fbdbmobdemo
description: "A demo Flutter application for the fbdb Firebird database access library."
version: 1.0.3
publish_to: 'none'
repository: https://github.com/hipercompl/fbdbmobdemo
homepage: https://github.com/hipercompl/fbdb
issue_tracker: https://github.com/hipercompl/fbdb/issues
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

screenshots:
  - description: An Android application connecting directly to a Firebird database.
    path: fbdbmobdemo_scr.png

topics:
  - database
  - firebird
  - fbclient

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fbdb: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - firebird.msg
